### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by GeoffreyPlitt** [balderdashy/skipper#103]
0.5.6 is not published to NPM

**Comment by mikermcneil** [comment]
@GeoffreyPlitt thanks for the heads up- on it

**Comment by GeoffreyPlitt** [comment]
+1

**Comment by mikermcneil** [comment]
ok published 0.5.7

**Comment by GeoffreyPlitt** [comment]
npm ERR! notarget No compatible version found: skipper-s3@'>=0.5.7 <0.6.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.5.0","0.5.1","0.5.2","0.5.3","0.5.4","0.5.5"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'ExpoSync'
npm ERR! notarget 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/ExpoSync/npm-debug.log

npm install returned exit code 1

Action failed: npm install

**Comment by GeoffreyPlitt** [comment]
Did this get published? NPM can't find 0.5.7 for me.
