### ISSUE TITLE
skipper make my REST-API timeout

### ISSUE THREAD

**Issue by smith64fx** [balderdashy/skipper#105]
When I activate skipper, I cannot connect to the backend anymore. It's just a timeout. The only message I get is:

```
express deprecated req.auth: Use basic-auth npm module instead node_modules/skipper/node_modules/connect/lib/utils.js:116:17
```

I activated it in the config/http.js file.

```
bodyParser: require('skipper')
```

I'm using SailsJS 0.12.0.-RC3 and Authentification via WebToken, Connection mostly via Sockets.
Any Idea?

**Comment by tjwebb** [comment]
What does "activate" mean? Skipper is installed and in use by default. Can you describe specifically what docs you're following and what you're trying to do?

**Comment by smith64fx** [comment]
Hi I fixed the problem.
If you uncomment the "bodyParser: require('skipper')" line in config/http.js the app won't work anymore. Deprecated?
