### ISSUE TITLE
Uploading program-generated files

### ISSUE THREAD

**Issue by Alaneor** [balderdashy/skipper#118]
Is it somehow possible to use Skipper to upload files which I generate inside the application?

All of the existing examples rely on the presence of `req.file()` method, but this only works for user-initiated file uploads. I need to be able to generate i.e. a pdf report and save it to the file storage.

My current workaround looks something like this:

```js
// Read the report
const file = fs.createReadStream('/path/to/report.pdf')
// Create an upstream receiver
const receiver = require('skipper-disk')({ /* options here */ }).receive()

receiver.write(file, () => {
  // called when upload is done, but with no arguments
})
```

The approach above works in regard of being able to write the file to the storage, but as I do not receive any information about the uploaded file, I have no reliable source to determine **where exactly** the file has been written.

How could I overcome this challenge with Skipper? Or is this use-case not covered at all?

Thanks for your help!

**Comment by Alaneor** [comment]
I figured it out! It required a bit of reverse-engineering, but it works. :)

This requires `skipper` to be installed alongside your project:

`npm install --save skipper`

And here is the function that converts an incoming raw stream into an object that you would normally get when you call `req.file()` during an http upload request.

```js
// Require all the dependencies needed
const Upstream = require('skipper/standalone/Upstream')
    , stream = require('stream')

/**
 * A transform stream that counts the bytes flowing through it
 *
 * The byte count can be read from this.byteCount property on the class' instance.
 */
class ByteCountStream extends stream.Transform {

  constructor(opts) {
    super(opts)
    this.byteCount = 0
  }

  _transform(chunk, encoding, done) {
    this.byteCount += chunk.length

    return done(null, chunk)
  }
}

/**
 * Convert a raw stream into Skipper's req.file()
 *
 * This makes it easy to upload generated files, ie. pdf reports and so on. Skipper only supports
 * uploading incoming http file uploads through its documented API, so we needed to develop a
 * workaround of sorts to allow this functionality.
 *
 * @param     {Stream}    inStream    Readable stream (fs stream, crypto stream, zlib stream...)
 * @return    {Stream}                An instance of Upstream, which is returned by Skipper when
 *                                    `req.file()` is called on http request object during upload
 */
function streamToFile(inStream) {
  // An Upstream is basically what we get when we call `req.file()` on an incoming request
  const file = new Upstream()
  // Because Skipper uses the stream's fd attribute to save the location information on the remote
  // filesystem's storage, we must pipe the stream through an intermediary. Why? Because an fs
  // read stream uses that same fd attribute to store it's file descriptor, which, when changed
  // during data transfer, will silently stop the flow of bytes.
  // As a nice side-effect, we can use this intermediary to count the bytes being uploaded, so we
  // have this information available just like when we would upload a file through http upload.
      , intermediary = new ByteCountStream()

  inStream.pipe(intermediary)

  // file.upload() only prepares the uploader to start receiving files - the .writeFile() actually
  // sends a file to the receiver. And, we must also tell the upstream that there are no more
  // files to be received, otherwise it will just keep waiting for more files to come
  file.writeFile(intermediary)
  file.noMoreFiles()

  // The `req.file()` is now fully simulated - continue as if http upload occured
  return file
}
```

**Comment by luispeerez** [comment]
@Alaneor I am trying to implement your ByteCountStream class on vanilla javascript, this is what I have:

`  function ByteCountStream(opts){
    //stream.Transform.constructor.apply(this, opts);
    stream.Transform.call(this, opts);
    /*
    this.byteCount = 0;

    this._transform = function(chunk, encoding, done){
      this.byteCount += chunk.length
      return done(null, chunk)
    }
    */
  }


  //ByteCountStream.prototype = new stream.Transform();
  ByteCountStream.prototype = Object.create(stream.Transform.prototype); // keeps the proto clean
  ByteCountStream.prototype = {
    byteCount: 0,
    _transform : function(chunk, encoding, done){
      this.byteCount += chunk.length
      return done(null, chunk)
    }
  }
  ByteCountStream.prototype.constructor = ByteCountStream;`

But everytime I use it, it throws the following error:  **"dest.on is not a function"** , can you help me with this?

**Comment by Alaneor** [comment]
```js
ByteCountStream.prototype = {
// ...
```

You are reassigning your prototype here, thus the `.on()` function which is defined on the Transform stream's prototype is not defined.

**Comment by luispeerez** [comment]
So, this will be the implementation?:

`  function ByteCountStream(opts){
    stream.Transform.call(this, opts);
    this.byteCount = 0;
    this._transform = function(chunk, encoding, done){
      this.byteCount += chunk.length
      return done(null, chunk)
    }    
  }
  ByteCountStream.prototype = Object.create(stream.Transform.prototype);
  ByteCountStream.prototype.constructor = ByteCountStream;`

**Comment by luispeerez** [comment]
[example.txt](https://github.com/balderdashy/skipper/files/285480/example.txt)

**Comment by luispeerez** [comment]
```
  function ByteCountStream(opts){
    stream.Transform.call(this, opts);
    this.byteCount = 0;
    this._transform = function(chunk, encoding, done){
      this.byteCount += chunk.length
      return done(null, chunk)
    }
  }
  ByteCountStream.prototype = Object.create(stream.Transform.prototype);

```
