### ISSUE TITLE
Include skipper-csv to the README?

### ISSUE THREAD

**Issue by hammady** [balderdashy/skipper#137]
I have developed [skipper-csv](https://github.com/hammady/skipper-csv) adapter to stream parse CSV uploads in-flight with a callback for each parsed row.
Is there a place for all contributed adapters or you just describe them in the README?

**Comment by irlnathan** [comment]
Howdy @hammady,

Check out [available-adapters](http://sailsjs.org/documentation/concepts/extending-sails/adapters/available-adapters).

Best, Irl
