### ISSUE TITLE
Empty upload fields

### ISSUE THREAD

**Issue by sixpounder** [balderdashy/skipper#23]
If e.g. a form is uploaded with an empty input field skipper fails with

Error: ETIMEOUT: An Upstream (`undefined`) timed out waiting for file(s). No files were sent after waiting 500ms.

even if .upload() method is not called at all. It is enough to call req.file('fileId') somewhere in the code (for example, to check if an optional file field has files in it)

Shouldn't it be fail safe when an input file field is present but empty? (req.file('something')._files.length == 0)

**Comment by mikermcneil** [comment]
Hey guys because of how this works, you need to handle the .upload() callback even for optional uploads. I'll write up an example

**Comment by radkodinev** [comment]
@mikermcneil An example would be great, thanks in advance :)

**Comment by mikermcneil** [comment]
@radkodinev @ReyesMagos @kvermeille @pavlo @sixpounder guys I think this is finally solved in all (or at least most) cases.  I tested extensively over the past few days.

In 0.5.5 i increased default ms before ETIMEOUT to 10 seconds (and also fixed an issue that was causing hanging issues when content-type errors from multiparty that occurred BEFORE .upload() was called on one or more upstreams were received)

**Comment by mikermcneil** [comment]
@radkodinev re example, try sending only text params (no files) to `POST /file/upload` in this sample app https://github.com/sails101/file-uploads/blob/master/api/controllers/FileController.js#L36

**Comment by radkodinev** [comment]
@mikermcneil Thanks. Version 0.5.5 works great in my application.

**Comment by sixpounder** [comment]
@mikermcneil works for me too. Thanks!

**Comment by moglash** [comment]
Hello guys i've still got this error when `file` parameter is missing
my code: https://gist.github.com/moglash/30723a81d10c873f21cb
```javascript
Error: EMAXBUFFER: An Upstream (`NOOP_file`) timed out before it was plugged into a receiver. It was still unused after waiting 4500ms. You can configure this timeout by changing the `maxTimeToBuffer` option.
    at null.<anonymous> (/home/moglash/webz/berry/berry-server-dev/node_modules/sails/node_modules/skipper/standalone/Upstream/Upstream.js:86:15)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
22 Feb 15:14:24 - [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by kvermeille** [comment]
@mikermcneil excellent!!!

**Comment by amberv0** [comment]
Yep, still happens in 0.5.5. 
But, in fact, when upload() is called, everything is ok. But when trying to do anything with req.file('<filaname>') error occurs. Or if to do something with req.file() first, and then call upload(), error also occurs. I believe this is the reason for the error in the gist above.
my sails is 0.11.0

Yet, what is weird in my case, the file should have been uploaded (since it was chosen in the form), but it doesn't seem to be. Figuring out why

**Comment by amberv0** [comment]
UPD
tried with  https://github.com/sails101/file-uploads
and also by copying controllers and views to a new sails project. 
NO PROBLEM EVER. 
It means that there seems to be some interference with some module or, hm, I don't know. Maybe policy. I'll try to find out.

**Comment by amberv0** [comment]
UPD
FOUND THE REASON:
In my form I didn't put
 enctype="multipart/form-data"
The problem is reproducible with https://github.com/sails101/file-uploads if to remove the enctype.

**Comment by lentiummmx** [comment]
It happens again, for me....

Error: EMAXBUFFER: An Upstream (`NOOP_kuponFile`) timed out before it was plugged into a receiver. It was still unused after waiting 4500ms. You can configure this timeout by changing the `maxTimeToBuffer` option.
    at null.<anonymous> (/home/phoenix/Repositories/git/miskupones/node_modules/sails/node_modules/skipper/standalone/Upstream/Upstream.js:86:15)
    at Timer.listOnTimeout (timers.js:110:15)


package,json
------------------
{
  "name": "skipper",
  "version": "0.5.5",
  "description": "Bodyparser for Express/Sails. Exposes simple API for streaming multiple files to disk, S3, etc. without buffering to a .tmp directory.",
  "main": "index.js",
  "directories": {},
  "scripts": {
    "test": "mocha && node -e \"require('skipper-adapter-tests')({module: require('skipper-disk')});\""
  },

**Comment by ArVan** [comment]
Happens to me also. Skipper version:  "0.5.5".

````
Error: EMAXBUFFER: An Upstream (`NOOP_audio`) timed out before it was plugged into a receiver. It was still unused after waiting 4500ms. You can configure this timeout by changing the `maxTimeToBuffer` option.
````

**Comment by wfpaisa** [comment]
Hi, I created a test error:
https://github.com/wfpaisa/SailsJS-EMAXBUFFER

**Comment by schematical** [comment]
Just started experiencing this today:

  Uncaught Error: EMAXBUFFER: An Upstream (`NOOP_file`) timed out before it was plugged into a receiver. It was still unused after waiting 4500ms. You can configure this timeout by changing the `maxTimeToBuffer` option.

**Comment by jamilnyc** [comment]
I get this error if I upload no files in the form with
sails 0.12.3
skipper-s3 0.5.6

How can I get it to ignore the input if the user doesn't upload anything.

**Comment by sebastialonso** [comment]
I'm still having this bug, same situation as the rest, if file doesn't come, `Error: EMAXBUFFER: An Upstream (`NOOP_icon`) timed out before it was plugged into a receiver.` triggers.

Can't the req.file('NAME') just be null or undefined when no file is uploaded? It seems awful that the whole object it's still there when no file whatsoever is uploaded.

**Comment by idoivri** [comment]
I'm also encountering this issue. Please do something with it...  I can't seem to be able to bypass the crash even when upload() is not being called.

**Comment by carloslfu** [comment]
I'm solved the problem of `req.file('something')._files.length` using `req._fileparser.upstreams.length` instead.

**Comment by bilal68** [comment]
where do i need to put this check..I am uploading from react and backend is sails...mgetting the same error in machine-as-action.js
