### ISSUE TITLE
Error ocurred when trying to access the file as a receiving stream

### ISSUE THREAD

**Issue by andyhu** [balderdashy/skipper#40]
When I use the code similar as in the documentation:
```
req.file('foo')
.on('error', function onError() { ... })
.on('finish', function onSuccess() { ... })
.pipe(receiving);
```
I received an error saying fd is `undefined` in line 82 of `skipper-disk/standalone/build-disk-recieve.js` 
```
    if (!__newFile.fd.match(/^\//)) {
```
I guess it's because of I didn't _attach the fd_ as instructed below in the documentation:
`Also bear in mind that you must first intercept the upstream and attach an fd (file descriptor) property to each incoming file stream.`

But how to `intercept the upstream and attach an fd`? I've tried all different ways but still got no luck.

Thanks!

**Comment by mikermcneil** [comment]
@farneman yup @andyhu's pr resolves this-- would you mind trying out the latest skipper-disk and skipper from npm and reporting back whenever you have a sec?  Thanks to you both!
