### ISSUE TITLE
docs don't make it clear what the file parameter should be and where it comes from

### ISSUE THREAD

**Issue by mgenev** [balderdashy/skipper#55]
it just says req.file('avatar') and that it's a file parameter. But how does the server know what to anticipate? Where is the file being named? I've figured it out, but it would be nice if the docs pointed the reader to a good direction about how to set it on the client...

**Comment by mikermcneil** [comment]
@mgenev ah good question.  This is the whole point behind Skipper- it knows what's being uploaded based on the field you pass to `req.file()`.  In the mean time, before your app-level code calls `req.file()` it uses streams2 and TCP backpressure to keep the bytes at bay.  It will never buffer more bytes in memory than allowed by the streams' `highWaterMark`s.  Just in case, there are a couple of failsafe timeouts (in addition to the default 120 second TCP timeout you get w/ node)
