### ISSUE TITLE
How to get file name instead of file full system path after uploaded?

### ISSUE THREAD

**Issue by hellowin** [balderdashy/skipper#57]
The callback after `upload` success is just an empty array. Did I miss something or it's what it should be?

**Comment by cburatto** [comment]
Thanks for clarifying. I personally prefer to have the full path and then decide how to break it down if needed. As it is, I can simply write some code to manipulate the file instead of rebuilding the path to get access to the file. But each case is different.

**Comment by hellowin** [comment]
@cburatto I see. Is Skipper it self will stay on this way? I think an API that return a filename is needed. But if it's doesn't make sense, it's ok since it's retrievable via full path.
I'm also afraid it will broke some existing user if the API changed :laughing:

**Comment by stavrosf4** [comment]
If I understand correctly what you're asking, you can take the full path stored in fd, use the split method with '/' on it, and the last element will always be the filename with the extension.

**Comment by hellowin** [comment]
@stavrosf4 yes it's true, I already mentioned in my comment above. I use:

```
function onUploadComplete (err, uploaded){
    if (err) { return res.serverError(err); }
    res.json({
      status : true,
      path: 'uploads/media/', //my own path relative to sails app location
      filename: uploaded[0].fd.split('/').reverse()[0] //my approach
    });
  });
```

But it's very inconvenient, because the path is depends on environment/ OS that we use. For example in Windows, it will result nothing. Because Windows use "\" not "/".

**Comment by albertpeiro** [comment]
I use this, which I find pretty neat (http://nodejs.org/api/path.html#path_path_basename_p_ext):

    var path = require('path');
    file.filename = path.basename(file.fd);

**Comment by hellowin** [comment]
@albertpeiro woah very nice, thank you very much. It looks like the core dev still focus on Sails core. I'll close this issue.
