### ISSUE TITLE
err is null on ETIMEOUT

### ISSUE THREAD

**Issue by gotmikhail** [balderdashy/skipper#58]
Trying to figure out why the `err` object returned is `null` when we have an `ETIMEOUT`.

Is that the intent? I'm actually intentionally creating an `ETIMEOUT` to document how to handle it from the client, but right now the server has nothing to differentiate.

I guess you could check the length of the `uploadedFiles`, but it seems to me like we should get an `err`.

**Comment by mikermcneil** [comment]
@gotmikhail Good question.  ETIMEOUT fires when `maxTimeToWaitForFirstFile` is exceeded (i.e. https://github.com/balderdashy/skipper/blob/master/standalone/Upstream/Upstream.js#L28).  This normally occurs when a request to one of your routes using skipper is taking a long time (slow connection), whether or not a file is actually being uploaded.  It would be great to have a test which triggered by writing the headers of an http request, then waiting a second and sending the body.  ETIMEOUT should fire and then we can replicate.  Thanks!

**Comment by mikermcneil** [comment]
@gotmikhail can you try out skipper@0.5.4 and skipper-disk@0.5.4?

**Comment by mikermcneil** [comment]
@gotmikhail this is resolved as of `0.5.4`.  In `0.5.5` i increased default ms before ETIMEOUT to 10 seconds (and also fixed an issue that was causing hanging issues when content-type errors from multiparty that occurred BEFORE `.upload()` was called on one or more upstreams were received)
