### ISSUE TITLE
Saving to Postgresql?

### ISSUE THREAD

**Issue by jurajpetrik** [balderdashy/skipper#76]
Is there a way to save the uploaded file to a postgresql db as a blob?  Perhaps leveraging waterline somehow? Or would I need to write an adapter for that?

**Comment by tjwebb** [comment]
Yea, the skipper README describes the skipper adapter spec. You can call if `skipper-postgresql` !

**Comment by tjwebb** [comment]
https://github.com/waterlinejs/skipper-postgresql
