### ISSUE TITLE
Sails V 0.11

### ISSUE THREAD

**Issue by AlexanderKozhevin** [balderdashy/skipper#85]
I'm trying to run the code from official website sails.org and having a trouble with skipper

Unable to parse HTTP body- error occurred :: 'Error: invalid json\n    at parse (/usr/local/lib/node_modules/sails/node_modules/skipper/node_modules/connect/node_modules/body-parser/lib/types/json.js:62:15)\n    at /usr/local/lib/node_modules/sails/node_modules/skipper/node_modules/connect/node_modules/body-parser/lib/read.js:91:18\n    at IncomingMessage.onEnd (/usr/local/lib/node_modules/sails/node_modules/skipper/node_modules/connect/node_modules/body-parser/node_modules/raw-body/index.js:136:7)\n    at IncomingMessage.g (events.js:199:16)\n    at IncomingMessage.emit (events.js:104:17)\n    at _stream_readable.js:908:16\n    at process._tickDomainCallback (node.js:381:11)'

**Comment by drj-io** [comment]
Sounds like you got a little further than I did on .11.  I'm trying to use S3

    	req.file('project_file').upload({
			adapter: require('skipper-s3'),
			key: sails.config.aws.s3_key,
			secret: sails.config.aws.s3_secret,
			bucket: sails.config.aws.project_upload_bucket,
			maxBytes: 1000000000 // 1GB max upload
		}, function (err, uploadedFiles) {

resulted in 

    events.js:143
      throw new Error('Uncaught, unspecified "error" event.');
            ^
Error: Uncaught, unspecified "error" event.
    at Writable.emit (events.js:143:13)
    at /Users/david/dev/p/rackfx/app/node_modules/skipper-s3/index.js:238:22
    at PassThrough.<anonymous> (/Users/david/dev/p/rackfx/app/node_modules/skipper-s3/node_modules/knox-mpu-alt/lib/multipartupload.js:328:16)
    at emitOne (events.js:82:20)
    at PassThrough.emit (events.js:166:7)
    at /Users/david/dev/p/rackfx/app/node_modules/sails/node_modules/skipper/standalone/Upstream/prototype.fatalIncomingError.js:65:17
    at Function.forEach (/Users/david/dev/p/rackfx/app/node_modules/sails/node_modules/lodash/dist/lodash.js:3298:15)


Pretty excited about streaming to S3, hoping that we can get this working.

**Comment by igorteton** [comment]
Seems this is more specific to skipper-s3: https://github.com/balderdashy/skipper-s3/issues/22

There is also advice how to find out more detailed error by uncommenting few lines.

Let's close this one and continue there
